import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Provider from '@/component/provider'
import ReduxProvider from '@/component/reduxProvider'
import MobileSlideBar from '@/component/mobileSlideBar'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full  min-h-screen relative h-full flex flex-col antialiased`}
      >
      <ReduxProvider>
      <Provider>
        <Header/>
        <div className="w-full h-auto min-h-screen relative flex flex-col top-16 sm:top-24">
        <MobileSlideBar/>
     
        {children}
        </div>

      </Provider>
      </ReduxProvider>
      </body>
    </html>
  );
}
